---
title: "Cast Vote Records"
---

This is a Quarto website.

```{r}
#| include: false
suppressPackageStartupMessages({
  library(tidyverse)
  library(gt)
  library(plotly)
})
```


# Coverage

## US House

Current coverage vs. elections

```{r}
#| echo: false
comp_tbl <- read_csv("data/tmp_ushou_harv.csv", show_col_types = FALSE)

comp_tbl |>
  select(cd, shareD_harv, N_harv, shareD_all, N_all) |>
  gt() |>
  sub_missing() |>
  cols_label_with(
    fn =
      \(x) case_match(x,
        "shareD_harv" ~ "Collected %D",
        "shareD_all" ~ "Election %D",
        "N_harv" ~ "Collected R + D",
        "N_all" ~ "Election R + D",
        "cd" ~ "CD",
      )
  ) |>
  fmt_integer(starts_with("N_")) |>
  fmt_number(starts_with("shareD_"), decimals = 2) |> 
  opt_interactive()

```

# Validation

## US House (district)

```{r}
#| echo: false
#| message: false
#| warning: false
cong_summary <- read_csv("data/by-district_val.csv", show_col_types = FALSE)

ush_plot <- plot_ly(
  data = cong_summary |> 
    filter(item == "US_REP"), 
  x = ~valid_DR, 
  y = ~harv_DR, 
  text = ~paste0("District: ", dist, "<br>Counties: ", harv_counties), 
  mode = "markers", 
  type = "scatter", 
  marker = list(size = 10),
  width = 650,
  height = 650)


ush_plot |> 
    layout(
        title = "2020 US House Validation",
         xaxis = list(title = "Actual Total Votes",
                      scaleanchor="y", scaleratio=1, 
                      dtick = 100000),
         yaxis = list(title = "CVR Total Votes",
                      scaleanchor="x", scaleratio=1,
                      dtick = 100000))  |> 
    add_trace(x = c(0, ~max(harv_DR, na.rm = T)), 
              y = c(0, ~max(harv_DR, na.rm = T)), 
              text = NA, mode = "lines", 
              marker = list(size = 1), 
              line = list(color = "rgba(0, 0, 0, 0.2)"), showlegend = FALSE)
```

## Presidential (county)

```{r}
#| echo: false
#| message: false
#| warning: false
pres_summary <- read_csv("data/by-county_val.csv", show_col_types = FALSE)

pres_plot <- plot_ly(data = pres_summary, 
                     x = ~valid_DR, 
                     y = ~harv_DR, 
                     text = ~paste0("County: ", county_name, ", ", st), 
                     mode = "markers", 
                     type = "scatter", 
                     marker = list(size = 10),
                     width = 650,
                     height = 650)

pres_plot |> 
  layout(title = "2020 Presidential Validation",
         xaxis = list(title = "Actual Total Votes",
                      scaleanchor="y", scaleratio=1,
                      dtick = 500000),
         yaxis = list(title = "CVR Total Votes",
                      scaleanchor="x", scaleratio=1,
                      dtick = 500000)) |> 
    add_trace(x = c(0, ~max(harv_DR, na.rm = T)), 
              y = c(0, ~max(harv_DR, na.rm = T)), 
              text = NA, mode = "lines", 
              marker = list(size = 1), 
              line = list(color = "rgba(0, 0, 0, 0.2)"), showlegend = FALSE)
```
